# Generated by Django 5.2 on 2025-04-29 16:21

import bugs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='reporter',
            field=models.ForeignKey(default=bugs.models.get_default_reporter, on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to=settings.AUTH_USER_MODEL),
        ),
    ]
